version: "3"
services:
  mecku_client:
    container_name: mecku_client
    build: ./client
    ports:
      - "4000:3000"
    links:
      - mecku_api

  mecku_api:
    container_name: mecku_api
    build: ./api
    ports: 
      - "9092:9092" 
    links:
      - mecku_mongodb

  mecku_mongodb:
    container_name: mecku_mongodb
    image: mongo:latest
    ports:
      - "27017-27019:27017-27019"
