/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const VALIDATE_NEW_USER = "VALIDATE_NEW_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const CHECK_AUTH_STATUS = "CHECK_AUTH_STATUS";
export const FORGOT_PASSWORD_START = "FORGOT_PASSWORD_START";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const UPDATE_REMAINING_SPACE = "UPDATE_REMAINING_SPACE";
export const GET_EMAIL_FROM_TOKEN = "GET_EMAIL_FROM_TOKEN";
export const NULLIFY_CATALOG = "NULLIFY_CATALOG";
export const NULLIFY_DASHBOARD_DATA = "NULLIFY_DASHBOARD_DATA";

/* JOBS */

export const CREATE_JOB = "CREATE_JOB";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const FETCH_ALL_JOBS = "FETCH_ALL_JOBS";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const DELETE_JOB = "DELETE_JOB";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const UPDATE_JOB_CANVAS = "UPDATE_JOB_CANVAS";
export const UPDATE_JOB_CANVAS_SUCCESS = "UPDATE_JOB_CANVAS_SUCCESS";
export const START_JOB = "START_JOB";
export const START_JOB_SUCCESS = "START_JOB_SUCCESS";
export const UPDATE_CANVAS_SUCCESS = "UPDATE_CANVAS_SUCCESS";

/* STAGES */
export const CREATE_STAGE = "CREATE_STAGE";
export const CREATE_STAGE_SUCCESS = "CREATE_STAGE_SUCCESS";
export const DELETE_STAGE = "DELETE_STAGE";
export const DELETE_STAGE_SUCCESS = "DELETE_STAGE_SUCCESS";
export const SAVE_STAGE = "SAVE_STAGE";
export const SAVE_STAGE_SUCCESS = "SAVE_STAGE_SUCCESS";

export const FETCH_SAMPLE_DATA = "FETCH_SAMPLE_DATA";
export const FETCH_SAMPLE_DATA_SUCCESS = "FETCH_SAMPLE_DATA_SUCCESS";

/* CATALOGS */
export const CREATE_CATALOG = "CREATE_CATALOG";
export const CREATE_CATALOG_SUCCESS = "CREATE_CATALOG_SUCCESS";
export const FETCH_CATALOG_STATUS = "FETCH_CATALOG_STATUS";
export const FETCH_CATALOG_STATUS_SUCCESS = "FETCH_CATALOG_STATUS_SUCCESS";
export const UPDATE_CATALOG_NAME = "UPDATE_CATALOG_NAME";
export const UPDATE_CATALOG_NAME_SUCCESS = "UPDATE_CATALOG_NAME_SUCCESS";
export const DELETE_CATALOG = "DELETE_CATALOG";
export const DELETE_CATALOG_SUCCESS = "DELETE_CATALOG_SUCCESS";
export const FETCH_ALL_CATALOGS = "FETCH_ALL_CATALOGS";
export const FETCH_ALL_CATALOGS_SUCCESS = "FETCH_ALL_CATALOGS_SUCCESS";
export const FETCH_CATALOG_REPORTS = "FETCH_CATALOG_REPORTS";
export const FETCH_CATALOG_REPORTS_SUCCESS = "FETCH_CATALOG_REPORTS_SUCCESS";
export const FETCH_CATALOG_FILES = "FETCH_CATALOG_FILES";
export const SET_ACTIVE_CATALOG = "SET_ACTIVE_CATALOG";
export const FETCH_BOX_TOKEN = "FETCH_BOX_TOKEN";
export const UPDATE_UPLOADED_FILE_LIST = "UPDATE_UPLOADED_FILE_LIST";
export const DELETE_CATALOG_FILE = "DELETE_CATALOG_FILE";
export const FILE_DELETE_SUCCESS = "FILE_DELETE_SUCCESS";
export const RUN_CATALOG = "RUN_CATALOG";
export const RESET_ACTIVE_CATALOG = "RESET_ACTIVE_CATALOG";
export const NULLIFY_ACTIVE_CATALOG = "NULLIFY_ACTIVE_CATALOG";
export const FETCH_SUMMARY_GRAPH = "FETCH_SUMMARY_GRAPH";
export const FETCH_SUMMARY_GRAPH_SUCCESS = "FETCH_SUMMARY_GRAPH_SUCCESS";
export const FETCH_CATALOG_GRAPH = "FETCH_CATALOG_GRAPH";
export const FETCH_CATALOG_GRAPH_SUCCESS = "FETCH_CATALOG_GRAPH_SUCCESS";
export const FETCH_DASHBOARD_REPORT = "FETCH_DASHBOARD_REPORT";
export const FETCH_DASHBOARD_REPORT_SUCCESS = "FETCH_DASHBOARD_REPORT_SUCCESS";
export const DOWNLOAD_CATALOG_REPORT = "DOWNLOAD_CATALOG_REPORT";
export const DOWNLOAD_CATALOG_REPORT_SUCCESS =
  "DOWNLOAD_CATALOG_REPORT_SUCCESS";
export const INITIATE_FILTER_GRAPH = "INITIATE_FILTER_GRAPH";
export const FILTER_GRAPH = "FILTER_GRAPH";
export const FETCH_USER_ACTIVITY = "FETCH_USER_ACTIVITY";
export const FETCH_USER_ACTIVITY_SUCCESS = "FETCH_USER_ACTIVITY_SUCCESS";
export const DOWNLOAD_MASKED_FILES = "DOWNLOAD_MASKED_FILES";

/* Demo View */

export const MASK_FILE = "MASK_FILE";
export const UNMASK_FILE = "UNMASK_FILE";

/* SEACH ENGINE */
export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS";
export const SEARCH_RESULTS_FETCH_SUCCESS = "SEARCH_RESULTS_FETCH_SUCCESS";
export const SEND_INVITE = "SEND_INVITE";
export const SEND_INVITE_SUCCESS = "SEND_INVITE_SUCCESS";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* TODOAPP*/
export const TODO_GET_LIST = "TODO_GET_LIST";
export const TODO_GET_LIST_SUCCESS = "TODO_GET_LIST_SUCCESS";
export const TODO_GET_LIST_ERROR = "TODO_GET_LIST_ERROR";
export const TODO_GET_LIST_WITH_FILTER = "TODO_GET_LIST_WITH_FILTER";
export const TODO_GET_LIST_WITH_ORDER = "TODO_GET_LIST_WITH_ORDER";
export const TODO_GET_LIST_SEARCH = "TODO_GET_LIST_SEARCH";
export const TODO_ADD_ITEM = "TODO_ADD_ITEM";
export const TODO_ADD_ITEM_SUCCESS = "TODO_ADD_ITEM_SUCCESS";
export const TODO_ADD_ITEM_ERROR = "TODO_ADD_ITEM_ERROR";
export const TODO_SELECTED_ITEMS_CHANGE = "TODO_SELECTED_ITEMS_CHANGE";

/* CHAT APP*/
export const CHAT_GET_CONTACTS = "CHAT_GET_CONTACTS";
export const CHAT_GET_CONTACTS_SUCCESS = "CHAT_GET_CONTACTS_SUCCESS";
export const CHAT_GET_CONTACTS_ERROR = "CHAT_GET_CONTACTS_ERROR";
export const CHAT_GET_CONVERSATIONS = "CHAT_GET_CONVERSATIONS";
export const CHAT_GET_CONVERSATIONS_SUCCESS = "CHAT_GET_CONVERSATIONS_SUCCESS";
export const CHAT_GET_CONVERSATIONS_ERROR = "CHAT_GET_CONVERSATIONS_ERROR";
export const CHAT_ADD_MESSAGE_TO_CONVERSATION =
  "CHAT_ADD_MESSAGE_TO_CONVERSATION";
export const CHAT_CREATE_CONVERSATION = "CHAT_CREATE_CONVERSATION";
export const CHAT_SEARCH_CONTACT = "CHAT_SEARCH_CONTACT";
export const CHAT_CHANGE_CONVERSATION = "CHAT_CHANGE_CONVERSATION";

/* SURVEY LIST APP*/
export const SURVEY_LIST_GET_LIST = "SURVEY_LIST_GET_LIST";
export const SURVEY_LIST_GET_LIST_SUCCESS = "SURVEY_LIST_GET_LIST_SUCCESS";
export const SURVEY_LIST_GET_LIST_ERROR = "SURVEY_LIST_GET_LIST_ERROR";
export const SURVEY_LIST_GET_LIST_WITH_FILTER =
  "SURVEY_LIST_GET_LIST_WITH_FILTER";
export const SURVEY_LIST_GET_LIST_WITH_ORDER =
  "SURVEY_LIST_GET_LIST_WITH_ORDER";
export const SURVEY_LIST_GET_LIST_SEARCH = "SURVEY_LIST_GET_LIST_SEARCH";
export const SURVEY_LIST_ADD_ITEM = "SURVEY_LIST_ADD_ITEM";
export const SURVEY_LIST_ADD_ITEM_SUCCESS = "SURVEY_LIST_ADD_ITEM_SUCCESS";
export const SURVEY_LIST_ADD_ITEM_ERROR = "SURVEY_LIST_ADD_ITEM_ERROR";
export const SURVEY_LIST_SELECTED_ITEMS_CHANGE =
  "SURVEY_LIST_SELECTED_ITEMS_CHANGE";

/* SURVEY DETAIL APP*/
export const SURVEY_GET_DETAILS = "SURVEY_GET_DETAILS";
export const SURVEY_GET_DETAILS_SUCCESS = "SURVEY_GET_DETAILS_SUCCESS";
export const SURVEY_GET_DETAILS_ERROR = "SURVEY_GET_DETAILS_ERROR";
export const SURVEY_DELETE_QUESTION = "SURVEY_DELETE_QUESTION";
export const SURVEY_SAVE = "SURVEY_SAVE";

/* General UI Related - CloudGov*/

export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_END = "FETCH_DATA_END";

export * from "./ui/actions";
export * from "./jobs/actions";
export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./search/actions";
// export * from "./dashboard/actions";
export * from "./todo/actions";
export * from "./chat/actions";
export * from "./surveyList/actions";
export * from "./surveyDetail/actions";
export * from "./demo/actions";
